const main_url = 'https://pokeapi.co/api/v2/pokemon/';
let card_number = 0;
let loading_counter = 10 - 1;
let language = 'de';
//let img = "";
let id = "";
//let designation = [];
//let bg_color = "";
let pokemon_main = [];
//let typs = [];
//let pokemon_species = [];
//let pokemon_typ = [];
//let pokemon_typs = [];
let like_list = [];
var opinion ="";

let language_other_data = [
    {
        "language": "de",
        "loading": "wir geladen",
        "speak": "Sprache",
        "typen": "Typen",
        "de": "Deutsch",
        "en": "Englisch",
        "fr": "Französisch",
        "it": "Italienisch",
        "es": "Spanisch",
        "ja": "Japanisch",
        "brand": "Pokédex",
        "load_more": "Pokémon wurde nicht gefunden. Bitte mehr Laden.",
        "about": "Übersicht",
        "base_stats": "Basisdaten",
        "evolution": "Evolution",
        "species": "Species",
        "height": "Höhe",
        "weight": "Gewicht",
        "abilities": "Fähigkeiten",
        "breeding": "Zucht",
        "gender": "Geschlecht",
        "egg_groups": "Gruppe",
        "egg_cycle": "Lebensraum",
        "hp": "Gesundheit",
        "attack": "Attacke",
        "defense": "Verteidigung",
        "sp_atk": "Sp. Att.",
        "sp_def": "Sp. Ver.",
        "speed": "Geschwindigkeit",
        "total": "Gesamt",
        "fact": "Fakten",
        "evolution_chain": "Evolutionskette",
        "level": "Lvl",
        "not_found" : "nicht gefunden",
        "search": "Suche dein Pokémon",
        "lvl": "Stufe",
        "10_cards": "10 weitere Karten Laden",
        "evo_not_found": "Es müssen noch folgende Karten geladen werden ",
        "evo_chain" :"Evolutionskette"
    },
    {
        "language": "en",
        "loading": "is loading",
        "speak": "Language",
        "typen": "Type",
        "de": "German",
        "en": "English",
        "fr": "French",
        "it": "Italian",
        "es": "Spanish",
        "ja": "Japanese",
        "brand": "Pokédex",
        "load_more": "Pokémon was not found. Please load more.",
        "about": "About",
        "base_stats": "Base Stats",
        "evolution": "Evolution",
        "species": "Species",
        "height": "Height",
        "weight": "Weight",
        "abilities": "Abilities",
        "breeding": "Breeding",
        "gender": "Gender",
        "egg_groups": "Egg Groups",
        "egg_cycle": "Egg Cycle",
        "hp": "HP",
        "attack": "Attack",
        "defense": "Defense",
        "sp_atk": "Sp. Atk",
        "sp_def": "Sp. Def",
        "speed": "Speed",
        "total": "Total",
        "fact": "Factual information",
        "not_found" : "Not found",
        "search": "Search your Pokémon",
        "lvl": "Level",
        "10_cards": "Load 10 more cards",
        "evo_not_found": "The following cards still need to be loaded ",
        "evo_chain" :"Evolution chain"
    },
    {
        "language": "fr",
        "loading": "est en cours de chargement",
        "speak": "Langue",
        "typen": "Type",
        "de": "Allemand",
        "en": "Anglais",
        "fr": "Français",
        "it": "Italien",
        "es": "Espagnol",
        "ja": "Japonais",
        "brand": "Pokédex",
        "load_more": "Pokémon n'a pas été trouvé. Veuillez charger davantage.",
        "about": "À propos",
        "base_stats": "Stats de base",
        "evolution": "Évolution",
        "species": "Espèce",
        "height": "Taille",
        "weight": "Poids",
        "abilities": "Capacités",
        "breeding": "Reproduction",
        "gender": "Genre",
        "egg_groups": "Groupes d'œufs",
        "egg_cycle": "Cycle d'œufs",
        "hp": "PV",
        "attack": "Attaque",
        "defense": "Défense",
        "sp_atk": "Atq. Spé.",
        "sp_def": "Déf. Spé.",
        "speed": "Vitesse",
        "total": "Total",
        "fact": "Faits",
        "not_found" : "pas trouvé",
        "search": "Cherche ton Pokémon",
        "lvl": "niveau",
        "10_cards": "Chargez 10 cartes supplémentaires",
        "evo_not_found": "Les cartes suivantes doivent encore être chargées",
        "evo_chain" :"Chaîne d'évolution"
    },
    {
        "language": "it",
        "loading": "sta caricando",
        "speak": "Lingua",
        "typen": "Tipo",
        "de": "Tedesco",
        "en": "Inglese",
        "fr": "Francese",
        "it": "Italiano",
        "es": "Spagnolo",
        "ja": "Giapponese",
        "brand": "Pokédex",
        "load_more": "Pokémon non è stato trovato. Si prega di caricare di più.",
        "about": "Informazioni",
        "base_stats": "Statistiche Base",
        "evolution": "Evoluzione",
        "species": "Specie",
        "height": "Altezza",
        "weight": "Peso",
        "abilities": "Abilità",
        "breeding": "Riproduzione",
        "gender": "Genere",
        "egg_groups": "Gruppi di Uova",
        "egg_cycle": "Ciclo delle Uova",
        "hp": "PS",
        "attack": "Attacco",
        "defense": "Difesa",
        "sp_atk": "Attacco Speciale",
        "sp_def": "Difesa Speciale",
        "speed": "Velocità",
        "total": "Totale",
        "fact": "I fatti",
        "not_found" : "non trovato",
        "search": "Cerca il tuo Pokémon",
        "lvl": "livello",
        "10_cards": "Carica altre 10 carte",
        "evo_not_found": "Le seguenti mappe devono ancora essere caricate",
        "evo_chain" :"Catena di evoluzione"
    },
    {
        "language": "es",
        "loading": "se está cargando",
        "speak": "Idioma",
        "typen": "Tipo",
        "de": "Alemán",
        "en": "Inglés",
        "fr": "Francés",
        "it": "Italiano",
        "es": "Español",
        "ja": "Japonés",
        "brand": "Pokédex",
        "load_more": "Pokémon no se encontró. Por favor, cargue más.",
        "about": "Acerca de",
        "base_stats": "Estadísticas Base",
        "evolution": "Evolución",
        "species": "Especie",
        "height": "Altura",
        "weight": "Peso",
        "abilities": "Habilidades",
        "breeding": "Reproducción",
        "gender": "Género",
        "egg_groups": "Grupos de Huevo",
        "egg_cycle": "Ciclo de Huevo",
        "hp": "PS",
        "attack": "Ataque",
        "defense": "Defensa",
        "sp_atk": "Ataque Especial",
        "sp_def": "Defensa Especial",
        "speed": "Velocidad",
        "total": "Total",
        "fact": "Hechos",
        "not_found" : "extraviado",
        "search": "Busca tu Pokémon",
        "lvl": "nivel",
        "10_cards": "Cargue 10 tarjetas más",
        "evo_not_found": "Aún es necesario cargar los siguientes mapas.",
        "evo_chain" :"Cadena de evolución"
    },
    {
        "language": "ja",
        "loading": "読み込み中です",
        "speak": "言語",
        "typen": "タイプ",
        "de": "ドイツ人",
        "en": "英語",
        "fr": "フランス語",
        "it": "イタリアの",
        "es": "スペイン語",
        "ja": "言語",
        "brand": "ポケデックス",
        "load_more": "ポケモンは見つかりませんでした。もう少し読み込んでください。",
        "about": "約",
        "base_stats": "基本ステータス",
        "evolution": "進化",
        "species": "種",
        "height": "身長",
        "weight": "体重",
        "abilities": "特性",
        "breeding": "育成",
        "gender": "性別",
        "egg_groups": "卵グループ",
        "egg_cycle": "卵サイクル",
        "hp": "体力",
        "attack": "攻撃力",
        "defense": "防御力",
        "sp_atk": "特攻",
        "sp_def": "特防",
        "speed": "速さ",
        "total": "合計",
        "fact": "事実",
        "not_found" : "見つかりません",
        "search": "あなたのポケモンを探してください",
        "lvl": "レベル",
        "10_cards": "さらに10枚のカードをロードする",
        "evo_not_found": "次のマップはまだロードする必要があります",
        "evo_chain" :"進化の連鎖"
    }
];

